In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression#binary classification tasks, where the goal is to 
#predict the probability that an instance belongs to a particular class (0 or 1, yes or no, etc.)
from sklearn.decomposition import PCA
#setting n_components=4 in PCA can be a useful approach for dimensionality reduction, 
#capturing variance, simplifying data, improving performance, and data visualization.
import pickle
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV


def selectpca(X_train,X_test,n):
        pca = PCA(n_components=n)
        pca = PCA(n_components = 5)
        X_train = pca.fit_transform(X_train)
        X_test = pca.transform(X_test)
        explained_variance = pca.explained_variance_ratio_
        return X_train, X_test, explained_variance
#def split_scalar(indep_X,dep_Y): #train test split preprocess
def split_scalar(X,y, test_size=0.2, random_state=0):         
        #X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
def cm_prediction(grid, X_test, y_test):
 
        grid_predictions = grid.predict(X_test)
        
        # Making the Confusion Matrix
        from sklearn.metrics import confusion_matrix
        cm = confusion_matrix(y_test, grid_predictions)     # classification algorithm ML using confusion matrix
        
        from sklearn.metrics import accuracy_score 
        from sklearn.metrics import classification_report
        
        Accuracy=accuracy_score(y_test, grid_predictions )        #using accuracy
        
        report=classification_report(y_test, grid_predictions)     #using report
        return  grid,Accuracy,report,grid_predictions,cm
def logistic(X_train,y_train):       
        # Fitting K-NN to the Training set
    from sklearn.linear_model import LogisticRegression
    param_grid = {'solver':['newton-cg', 'lbfgs', 'liblinear', 'saga'],
             'penalty':['l2']} 
    grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')         
    grid.fit(X_train, y_train)
    grid,Accuracy,report,grid_predictions,cm=cm_prediction(grid,X_test,y_test)   #cm_prediction called here
    return grid,Accuracy,report,grid_predictions,cm 
      
def selectk_Classification(acclog): 
    
    dataframe=pd.DataFrame(index=['PCA'],columns=['Logistic'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        
    return dataframe

In [11]:
dataset=pd.read_csv("diabetes.csv",index_col=None)
dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [12]:
dataset.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [13]:
X=dataset[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age',]]
y=dataset['Outcome']

In [14]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [16]:
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [17]:

acclog=[]

In [18]:
X_train, X_test, y_train, y_test=split_scalar(X,y, test_size=0.2, random_state=0)   
    
        
grid,Accuracy,report,grid_predictions,cm=logistic(X_train,y_train)
acclog.append(Accuracy)


    
#result=selectk_Classification(acclog)

Fitting 5 folds for each of 4 candidates, totalling 20 fits

In [19]:
result=selectk_Classification(acclog)
#5

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3108\2205248095.py:63: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Logistic'][idex]=acclog[number]

In [20]:
result
#5

     Logistic
PCA  0.824675

In [21]:
re=grid.cv_results_

In [22]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001231,0.000781,0.013525,0.000000,l2,newton-cg,"{'penalty': 'l2', 'solver': 'newton-cg'}",0.706796,0.796219,0.744242,0.706906,0.794774,0.749787,0.039743,1
1,0.002820,0.002451,0.011666,0.005909,l2,lbfgs,"{'penalty': 'l2', 'solver': 'lbfgs'}",0.706796,0.796219,0.744242,0.706906,0.794774,0.749787,0.039743,1
2,0.003128,0.006256,0.011173,0.005783,l2,liblinear,"{'penalty': 'l2', 'solver': 'liblinear'}",0.706796,0.796219,0.744242,0.699736,0.794774,0.748353,0.041361,4
3,0.006474,0.004828,0.008847,0.003359,l2,saga,"{'penalty': 'l2', 'solver': 'saga'}",0.706796,0.796219,0.744242,0.706906,0.794774,0.749787,0.039743,1

In [23]:
grid.predict([[1,85,66,29,0,26.6,0.351,31]])

array([1], dtype=int64)